-- ==============================================================================
-- STYLEGT - Esquema y Datos Iniciales para Supabase
-- ==============================================================================

-- 1. Limpieza preventiva (si ya existían tablas con estos nombres)
DROP TABLE IF EXISTS items_pedido CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS variantes_producto CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;

-- 2. Creación de Tablas

-- Tabla de Categorías
CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL
);

-- Tabla de Productos
CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio NUMERIC(10, 2) NOT NULL,
    imagen_url TEXT,
    categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tabla de Variantes (Talla, Color, Stock)
CREATE TABLE variantes_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
    color TEXT NOT NULL,
    talla TEXT NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0
);

-- Tabla de Pedidos (Checkout)
CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente TEXT NOT NULL,
    telefono TEXT NOT NULL,
    direccion_envio TEXT NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    estado TEXT DEFAULT 'pendiente',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tabla de Ítems del Pedido
CREATE TABLE items_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT REFERENCES pedidos(id) ON DELETE CASCADE,
    variante_id BIGINT REFERENCES variantes_producto(id) ON DELETE SET NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL
);

-- 3. Habilitar Row Level Security (RLS) y Políticas de Acceso Público
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE variantes_producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE items_pedido ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública para el catálogo
CREATE POLICY "Lectura publica de categorias" ON categorias FOR SELECT USING (true);
CREATE POLICY "Lectura publica de productos" ON productos FOR SELECT USING (true);
CREATE POLICY "Lectura publica de variantes" ON variantes_producto FOR SELECT USING (true);

-- Políticas de creación y consulta de pedidos para clientes
CREATE POLICY "Insercion publica de pedidos" ON pedidos FOR INSERT WITH CHECK (true);
CREATE POLICY "Lectura de pedidos creados" ON pedidos FOR SELECT USING (true);
CREATE POLICY "Insercion publica de items_pedido" ON items_pedido FOR INSERT WITH CHECK (true);

-- 4. Inserción de Categorías
INSERT INTO categorias (id, nombre) VALUES
(1, 'Camisetas & Tops'),
(2, 'Pantalones'),
(3, 'Chaquetas & Abrigos'),
(4, 'Prendas de Punto');

-- 5. Inserción de Productos
INSERT INTO productos (id, nombre, descripcion, precio, imagen_url, categoria_id, activo) VALUES
(
    1,
    'Camiseta Oversize Heavy Cotton',
    'Confeccionada en algodón pesado de 240 GSM. Caída relajada con cuello acanalado reforzado.',
    38.00,
    'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    1,
    true
),
(
    2,
    'Pantalón Pleated Relaxed Fit',
    'Corte amplio con pinzas frontales y tejido fluido. Ideal para estilismos formales y casuales.',
    65.00,
    'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    2,
    true
),
(
    3,
    'Sobrecamisa de Lana Estructurada',
    'Prenda exterior versátil con cierre frontal por botones ocultos y bolsillos laterales discretos.',
    89.00,
    'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop&q=80',
    3,
    true
),
(
    4,
    'Sudadera Minimalista Cuello Redondo',
    'Interior afelpado de alta densidad sin logos ni estampados. Silueta limpia y confortable.',
    54.00,
    'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    1,
    true
),
(
    5,
    'Blazer Sastrería Desestructurado',
    'Diseño ligero sin hombreras que equilibra elegancia y comodidad para el día a día.',
    120.00,
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
    3,
    true
),
(
    6,
    'Jersey de Cuello Alto en Punto Fino',
    'Tejido elástico de tacto suave diseñado para vestir en capas en climas frescos.',
    62.00,
    'https://images.unsplash.com/photo-1614975058789-41316d0e2e9c?w=800&auto=format&fit=crop&q=80',
    4,
    true
);

-- Reiniciar secuencias de IDs para evitar desajustes
SELECT setval('categorias_id_seq', (SELECT MAX(id) FROM categorias));
SELECT setval('productos_id_seq', (SELECT MAX(id) FROM productos));

-- 6. Inserción de Variantes de Producto (Colores, Tallas y Stock)

-- Producto 1: Camiseta Oversize Heavy Cotton
INSERT INTO variantes_producto (producto_id, color, talla, stock) VALUES
(1, 'Negro', 'S', 12),
(1, 'Negro', 'M', 18),
(1, 'Negro', 'L', 15),
(1, 'Negro', 'XL', 8),
(1, 'Blanco', 'S', 10),
(1, 'Blanco', 'M', 20),
(1, 'Blanco', 'L', 14),
(1, 'Verde Oliva', 'M', 12),
(1, 'Verde Oliva', 'L', 10);

-- Producto 2: Pantalón Pleated Relaxed Fit
INSERT INTO variantes_producto (producto_id, color, talla, stock) VALUES
(2, 'Negro', 'S', 8),
(2, 'Negro', 'M', 14),
(2, 'Negro', 'L', 10),
(2, 'Beige', 'S', 6),
(2, 'Beige', 'M', 12),
(2, 'Beige', 'L', 8),
(2, 'Gris', 'M', 10),
(2, 'Gris', 'L', 7);

-- Producto 3: Sobrecamisa de Lana Estructurada
INSERT INTO variantes_producto (producto_id, color, talla, stock) VALUES
(3, 'Negro', 'M', 8),
(3, 'Negro', 'L', 10),
(3, 'Camel', 'M', 6),
(3, 'Camel', 'L', 9);

-- Producto 4: Sudadera Minimalista Cuello Redondo
INSERT INTO variantes_producto (producto_id, color, talla, stock) VALUES
(4, 'Gris', 'S', 15),
(4, 'Gris', 'M', 22),
(4, 'Gris', 'L', 18),
(4, 'Negro', 'M', 14),
(4, 'Negro', 'L', 16);

-- Producto 5: Blazer Sastrería Desestructurado
INSERT INTO variantes_producto (producto_id, color, talla, stock) VALUES
(5, 'Negro', 'M', 5),
(5, 'Negro', 'L', 7),
(5, 'Azul Marino', 'M', 6),
(5, 'Azul Marino', 'L', 4);

-- Producto 6: Jersey de Cuello Alto en Punto Fino
INSERT INTO variantes_producto (producto_id, color, talla, stock) VALUES
(6, 'Negro', 'S', 10),
(6, 'Negro', 'M', 15),
(6, 'Negro', 'L', 12),
(6, 'Beige', 'M', 9),
(6, 'Beige', 'L', 8);

-- Políticas para permitir actualizar desde el panel de admin
CREATE POLICY "Actualizacion publica de productos" ON productos FOR UPDATE USING (true);
CREATE POLICY "Actualizacion publica de variantes" ON variantes_producto FOR UPDATE USING (true);

-- ==============================================================================
-- 7. Configuración de Storage (Imágenes de Productos)
-- ==============================================================================

-- Nota: Debes crear manualmente un bucket llamado 'productos' en Supabase Storage y hacerlo Público.

-- Permitir que cualquier usuario (o admin) suba imágenes al bucket 'productos'
CREATE POLICY "Permitir subida de imagenes publicas" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'productos');
CREATE POLICY "Permitir lectura de imagenes" ON storage.objects FOR SELECT TO public USING (bucket_id = 'productos');
